### PR TITLE
adding clnrod

### PR DESCRIPTION
**Pull request by daywalker90**
Plugin to allow/deny incoming channel opens based on lists and/or a custom rule: https://github.com/daywalker90/clnrod

### CODE REVIEW

**Comment by chrisguida** [comment]
Looks very useful, I think this might be the first channel acceptor plugin I've seen for CLN!

ACK 69a5d61

**Comment by vincenzopalazzo** [comment]
It is possible to remove the merge commit? otherwise, it looks good to me, I had a custom version, but I do not think it is worth keeping two plugins.

Due to that mine is not advanced like the @daywalker90 I will drop mine :) and cloning the clnrod

**Comment by daywalker90** [comment]
updated to 0.2.1 to have a default reject message.

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/lightningd/plugins/pull/533/commits/0e4558a8d70c49f0d1c968869794d6f0e7fafb4d

**Pull request merged**
