### PR TITLE
archive plugin sparko

### PR DESCRIPTION
**Pull request by daywalker90**
@fiatjaf  This plugin is archived and has no tests. It should therefore be removed.

### CODE REVIEW

**Comment by fiatjaf** [comment]
I agree.

**Comment by chrisguida** [comment]
ACK 58de1ed0595a24a53510dc89ede96a00acca648e

Are there any other plugins that do something similar?

Maybe we can keep around a list of old plugins that are no longer maintained but do something useful and might serve as examples for new devs?

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/lightningd/plugins/pull/517/commits/58de1ed0595a24a53510dc89ede96a00acca648e

**Comment by chrisguida** [comment]
I think keeping old plugins around in the "archived" section is useful for new devs looking for old plugins that do something interesting and which no new plugin currently does. Otherwise they just disappear forever.

Closing unless a compelling argument can be made as to why sparko is causing harm by remaining in the archived section.

**Review by chrisguida — CHANGES_REQUESTED** [review]
I think we should move this to the archived section rather than removing it entirely.

**Review by chrisguida — APPROVED** [review]

**Review by chrisguida — APPROVED** [review]
ACK ebc44fd

**Pull request merged**
