### PR TITLE
Misc Jit-rebalance plugin enhancements

### PR DESCRIPTION
**Pull request by darosior**
Just need to add tests now (and potentially the second point of https://github.com/lightningd/plugins/issues/120#issue-625570619)

Based on https://github.com/lightningd/plugins/pull/115

### CODE REVIEW

**Comment by cdecker** [comment]
Rebased on top of `master` after #115 got merged.

**Comment by darosior** [comment]
@codecov for once I made you happy !

**Comment by cdecker** [comment]
> @codecov for once I made you happy !

I've never seen it so happy! Thank you for taking the time to add tests ^^

**Comment by darosior** [comment]
Added a commit for https://github.com/lightningd/plugins/issues/120#issuecomment-635885036

**Comment by darosior** [comment]
Restarted the flaky Travis job. I think we can take care of the "don't retry excluded channels too soon" feature in another PR

**Comment by cdecker** [comment]
ACK https://github.com/lightningd/plugins/pull/121/commits/6fbc5cdb6dc08496d65fdf554b6da0472c7c0441

**Comment by cdecker** [comment]
Excellent work @darosior :+1:

**Pull request merged**
