### PR TITLE
Python formatting

### PR DESCRIPTION
**Pull request by daywalker90**
Added [ruff](https://docs.astral.sh/ruff/formatter/) to pyproject.toml and included only files from this repo so submodules don't get touched.

Simply install ruff from the pyproject.toml or directly with pip and 

```
ruff format
```

will format all of this repo's files.

This is ontop of #567

### CODE REVIEW

**Comment by daywalker90** [comment]
it didnt have any locally, must be github being weird

**Comment by chrisguida** [comment]
@sip-21 can you review? I know you had a formatter you were using as well

**Comment by chrisguida** [comment]
ACK https://github.com/lightningd/plugins/pull/568/commits/52925e85b17b36ddbce6327b98c359dfab344ca2

**Comment by chrisguida** [comment]
ACK https://github.com/lightningd/plugins/pull/568/commits/bd9bceeee7e0eed88b3e455e59efe89328404e21

**Pull request merged**
