### PR TITLE
Update Nostrify v1.0.1

### PR DESCRIPTION
**Pull request by joelklabo**

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/lightningd/plugins/pull/436/commits/0fa725946d469e3cb423a5df3c01c723e8b6fb87

**Review by cdecker — DISMISSED** [review]

**Review by cdecker — DISMISSED** [review]

**Comment by cdecker** [comment]
@Mergifyio queue

**Comment by cdecker** [comment]
@Mergifyio requeue

**Comment by joelklabo** [comment]
Sorry @cdecker found a bug in the release

**Comment by cdecker** [comment]
No worries :-)

**Comment by cdecker** [comment]
@Mergifyio rebase
@Mergifyio requeue

**Pull request merged**
