### PR TITLE
Sling

### PR DESCRIPTION
**Pull request by daywalker90**
This is a rebalance plugins that builds upon circular (currently unmaintained) and has these key differences:

- add command to describe a rebalance job that will continously run in the background
- status overview for all added jobs
- statistics for every job
- no deadlocks (*knock on wood*)

### CODE REVIEW

**Comment by daywalker90** [comment]
rebased and updated sling to v1.1.1 which had a small bugfix when showing detailed stats on nodes that dropped from gossip.

**Comment by chrisguida** [comment]
Needs rebase

**Comment by daywalker90** [comment]
rebased, squashed and fixed tests for master

**Comment by chrisguida** [comment]
Needs another rebase heh

**Comment by daywalker90** [comment]
rebased

**Comment by chrisguida** [comment]
ACK c8eba1f4e6a2e847d6432bdd5398123db5a8fe0a

**Pull request merged**
