### PR TITLE
Fix rebalance plugin

### PR DESCRIPTION
**Pull request by gallizoltan**
rebalance plugin is maintained

### CODE REVIEW

**Comment by sip-21** [comment]
Hi @gallizoltan , there seems to be an issue with the CI tests for PRs moving a plugin out of the `archived` directory. Will investigate asap.

**Comment by sip-21** [comment]
@gallizoltan  Once https://github.com/lightningd/plugins/pull/503 is merged you can move ahead with this PR. According to [this](https://github.com/sip-23-23/plugins/actions/runs/8191586761/job/22401134529) workflow run (which I used for testing my CI workflow changes ) the rebalance plugin tests won't pass yet, though.

**Comment by cdecker** [comment]
Merged #503 👍

**Comment by gallizoltan** [comment]
@sip-21 I'm working on the `rebalance` tests. Besides, are you sure #503 helps? As I see, the integration tests still cannot find the `rebalance` directory here.

**Comment by chrisguida** [comment]
Looks like the problem may be that your branch is named `master`... @sip-21 can we work around this?

https://github.com/lightningd/plugins/actions/runs/8202656311/job/22433872620?pr=502#step:8:146

**Comment by chrisguida** [comment]
Please rebase on #506 and make sure CI passes

**Comment by gallizoltan** [comment]
@chrisguida @sip-21 I've made the rebase, checks have passed, please review, I think it is ready for merge! 😎

**Comment by chrisguida** [comment]
ACK 4a87751ae7c3714f21d4bcad798bf406a0bf3704

**Comment by chrisguida** [comment]
Thanks again @gallizoltan for fixing rebalance! :tada:

**Pull request merged**
