### PR TITLE
exposed a method to cancel all outstanding test plugins

### PR DESCRIPTION
**Pull request by renepickhardt**
especially uncertain about line 240
because I don't know what actually happens on a protocol level if one tries to cancel an htlc that has already been canceled. would be bad if the channel gets failed. it wasn't clearly to me specified at: https://github.com/lightningnetwork/lightning-rfc/blob/master/02-peer-protocol.md#removing-an-htlc-update_fulfill_htlc-update_fail_htlc-and-update_fail_malformed_htlc

if that was a problem anyway we would still have race condition problems if the call comes roughly at the same time when the timeout timer triggers anyway

### CODE REVIEW

**Comment by renepickhardt** [comment]
this method does not work! in the current form as it triggers this exception: 

```
INFO    plugin-paytest.py:   File \"/home/rpickhardt/lnplugins/plugins/paytest/paytest.py\", line 245, in rejectpaytests
INFO    plugin-paytest.py:     for secret in plugin.pending.keys():
INFO    plugin-paytest.py: RuntimeError: dictionary changed size during iteration
```

the `timout` function is killing the secrete I have a fix will update the PR soonish

**Comment by cdecker** [comment]
@Mergifyio rebase

**Comment by chrisguida** [comment]
Needs rebase, `paytest` has been removed from the actively maintained plugins list to get CI running again, but feel free to add it back :)

**Comment by chrisguida** [comment]
Closing this as `paytest` is [no longer maintained](https://github.com/lightningd/plugins/pull/484). Feel free to resurrect it by opening a PR that moves it out of archived :)

**Pull request closed without merging**
