### PR TITLE
commando: change underscore to dash

### LINKED ISSUE #343: commando-reader=<id>: unrecognized option (is commando_reader)
No matter if used as a command-line parameter with `--commando-reader=<id>` or in config file as `commando-reader=<id>`

The option which works is `commando_reader` in the config file and `--commando_reader` in command line of `lightningd`.

So no dash, but underscore. Will do a PR for the readme in a moment.

### PR DESCRIPTION
**Pull request by jsarenik**
Fixes #343

### CODE REVIEW

**Comment by jsarenik** [comment]
Just a note that I was not trying for a while to use commando since its Python dependency could not be compiled on Alpine Linux. Now it works well. Kudos to @jb55 for triggering my retry (by doing [lnlink](https://github.com/jb55/lnlink)).

**Comment by laanwj** [comment]
TBH I'd fix it the other way around (fix the plugin instead of the docs), it's more consistent with other plugin's arguments.

**Comment by jsarenik** [comment]
> TBH I'd fix it the other way around (fix the plugin instead of the docs), it's more consistent with other plugin's arguments and UNIX argument spelling in general.

Done. Thank you for feed-back.

**Comment by laanwj** [comment]
Thanks, looks good to me now!

**Pull request merged**
