### PR TITLE
feeadjuster: quick fix to get it back working due to listconfigs API changes

### PR DESCRIPTION
**Pull request by telelvis**
This PR gets feeadjuster up to date with recent changes in Listconfigs API where it now returns object instead of a list.
Makes plugin functional again.

### CODE REVIEW

**Comment by chrisguida** [comment]
You'll need to move this out of `archived` to get the CI to test it

**Review by chrisguida — CHANGES_REQUESTED** [review]
You'll need to move `feeadjuster` out of `archived` to get the CI to test it

**Comment by telelvis** [comment]
updated! please have a look.

**Comment by chrisguida** [comment]
ACK11273e09eca7004eddde8273e83b76caeb5056bd

**Comment by chrisguida** [comment]
`feeadjuster` lives! congrats :tada:

**Pull request merged**
