### PR TITLE
Add support for signet

### PR DESCRIPTION
**Pull request by Amperstrand**
Tested with

```
lightningd --network=signet --log-level=debug --disable-plugin bcli  --plugin ~/plugins/sauron/sauron.py --sauron-api-endpoint https://mutinynet.com/api
```

Should also work for https://mempool.space/signet/api

### CODE REVIEW

**Comment by chrisguida** [comment]
@mergifyio rebase

**Comment by chrisguida** [comment]
@mergifyio rebase

**Comment by chrisguida** [comment]
@kodylow was the last person to maintain `sauron`, I spoke to him and he says trustedcoin and futhark may be better.

Also he has a newer repo here that includes a go version and more stuff: https://github.com/Kodylow/sauron

@cdecker should we just merge this in or should we update `sauron` to point somewhere else?

**Comment by cdecker** [comment]
@Mergifyio rebase

**Pull request merged**
