### PR TITLE
chore: renames RPC feeadjusttoggle to feeadjust-toggle

### PR DESCRIPTION
**Pull request by m-schmoock**
After small chat with cdecker, using dash/minus in RPC name is good and will be translated to underscore in pyln on the fly.

### CODE REVIEW

**Comment by m-schmoock** [comment]
@gallizoltan as mentioned earlier ...

**Comment by m-schmoock** [comment]
Also: do we want `feeadjuster-toggle` or `feeadjust-toggle` ? I tend to the first. Second one is only better if we rename the whole plugin, which I dont like.

**Comment by gallizoltan** [comment]
tACK fb05a96
Now I can call `feeadjuster-toggle` (with dash) from command line and `feeadjuster_toggle` (with underscore) from python RPC.

**Comment by gallizoltan** [comment]
> Also: do we want `feeadjuster-toggle` or `feeadjust-toggle` ? I tend to the first. Second one is only better if we rename the whole plugin, which I dont like.

I think the current `feeadjuster-toggle` is good in the code. Maybe the commit message could be more precise, but does not matter.

**Pull request merged**
