### PR TITLE
holdinvoice

### PR DESCRIPTION
**Pull request by daywalker90**
Adds a plugin to hold invoices aka hodlinvoices. For more info see https://github.com/daywalker90/holdinvoice#documentation

### CODE REVIEW

**Comment by cdecker** [comment]
Very nice :+1: Thanks for bearing with us @daywalker90, and sorry for the late move to the plugin repository

ACK https://github.com/lightningd/plugins/pull/482/commits/e56f197372a91cf9d6de4e85f929350fdec181c5

**Comment by cdecker** [comment]
Rebasing to get the CI running again.

**Comment by daywalker90** [comment]
I tihnk the CI is broken: `ERROR: Package 'pyln-client' requires a different Python: 3.7.17 not in '<4.0,>=3.8'`

**Comment by chrisguida** [comment]
Yep, it seems that the CI has issues with python dependencies, will dig more tomorrow.

Still familiarizing myself with this system...

**Comment by chrisguida** [comment]
@cdecker looks like DEVELOPER is gone, should we just remove it? Or replace it with DEBUGBUILD? Or we can just keep it as is, it seems to set DEBUGBUILD now: https://github.com/ElementsProject/lightning/blob/master/configure#L252

**Comment by chrisguida** [comment]
Also looks like we can remove testing on python 3.7 and add a few more recent versions, since pyln-client doesn't support 3.7 anymore

**Comment by cdecker** [comment]
The `DEVELOPER` build-time flag is gone for good, replaced with the run-time flag `--developer`, so we can just remove any extra handling, or where needed use `listconfigs` to determine if we have the extended API available.

**Comment by chrisguida** [comment]
@daywalker90 I think this PR is next up, right? If so, please rebase on master and let's see if the tests pass

**Comment by chrisguida** [comment]
Actually let's try this

@Mergifyio rebase

**Comment by chrisguida** [comment]
@mergifyio rebase

**Comment by daywalker90** [comment]
> @daywalker90 I think this PR is next up, right? If so, please rebase on master and let's see if the tests pass

no imo, #486 -> #485 -> #487 -> then this

**Comment by chrisguida** [comment]
@daywalker90 SGTM

**Comment by daywalker90** [comment]
rebased and fixed tests for master

**Comment by chrisguida** [comment]
Looks great! Thanks for building this!! :tada:

**Pull request merged**
