### PR TITLE
Add `circular` to the list of plugins

### PR DESCRIPTION
**Pull request by giovannizotta**
`circular` is a plugin that helps routing nodes rebalance their channels. It features a custom pathfinding algorithm that gathers liquidity information from failed payments and uses it to be as effective as possible.

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/lightningd/plugins/pull/391/commits/f578f09ca9486b59c7b2406b2d4627fb113921e1****

**Comment by giovannizotta** [comment]
I noticed there were some conflicts because another plugin was added after I did this PR. I resolved them, is there anything else I need to do?

**Comment by cdecker** [comment]
I went ahead and rebased on top of `master`, so it applies cleanly now.

**Comment by giovannizotta** [comment]
@cdecker do I have to do something to merge this? I'm not allowed to author commits, so I guess you should do it. Let me know if I can help

**Comment by cdecker** [comment]
That's quite alright, looks like we need a rebase due to a conflict on `README.md`, but I can do that.

**Pull request merged**
