### PR TITLE
feeadjuster: basefee switch

### PR DESCRIPTION
**Pull request by m-schmoock**
- make dynamic adjustments of the base fee optional and off per default.
Currently only affects median strategy

- fixes some bugs, breakages and testcases along the way

### CODE REVIEW

**Comment by grubles** [comment]
Finally got a chance to test this. The exclude list keeps the channels' fees from being changed by feeadjuster at node start, but if a forward occurs after start, the fees are adjusted despite being in the exclude list.

**Comment by m-schmoock** [comment]
Yes I know that this is still missing.
I'm really busy with other stuff recently :(

**Comment by chrisguida** [comment]
Needs rebase

**Comment by chrisguida** [comment]
This has been merged as part of #525.

Thanks for the great work!!

**Pull request closed without merging**
