### PR TITLE
Add badges for currencyrate plugin

### PR DESCRIPTION
**Pull request by sip-21**
* Add `main` and `nightly` badges for `currencyrate` plugin on _README.md_

### CODE REVIEW

**Comment by chrisguida** [comment]
Do we need to do an update like this every time we add tests?

Where are you getting the new badge URLs from?

Perhaps we can just mark all the plugins with missing tests as failing?

**Comment by sip-21** [comment]
We could add URLs for all plugins, but it will not look nice. It will display a red badge with the "Resource missing" or similar text. 

But yes, thinking more about it, we could add default JSON data in the _.badges_ branch for displaying badges for those plugins that still have no tests.

**Comment by chrisguida** [comment]
Let's add badges for `bolt12-prism` as well https://github.com/lightningd/plugins/pull/519

**Comment by chrisguida** [comment]
Merging this for now, we can do something more complicated later :)

ACK 5911628

**Review by chrisguida — APPROVED** [review]

**Pull request merged**
