### PR TITLE
rebalance: improve the feeadjust availability check

### PR DESCRIPTION
**Pull request by m-schmoock**
This can be done without invoking RPC help. Sorry I didnt get this
earlier ;)

### CODE REVIEW

**Comment by m-schmoock** [comment]
@gallizoltan does this also work for you?

**Comment by gallizoltan** [comment]
Looks good to me, thanks! :)

**Comment by gallizoltan** [comment]
What happens if I call this?
```
print(callable(getattr(plugin.rpc, "this_function_does_not_exist")))
```

**Comment by m-schmoock** [comment]
> ```
> print(callable(getattr(plugin.rpc, "this_function_does_not_exist")))
> ```

Hm, just tried and it gives me: `plugin-rebalance.py: True`
Do you know why?

**Pull request closed without merging**
