### PR TITLE
feeadjuster: setchannelfee mandatory parameters

### PR DESCRIPTION
**Pull request by gallizoltan**
- feeadjuster keeps crashing since ages
- this may not be the perfect solution, but fixes the crash

### CODE REVIEW

**Comment by gallizoltan** [comment]
Hi @m-schmoock, look what I did here! :)

**Comment by m-schmoock** [comment]
@gallizoltan can you post a stacktrace and describe when/how it crashes?
I currently can't see why passing optional None values will help on this line.

Latest version of the plugin seems working for me and the tests are green except a timeout on `test_feeadjuster_imbalance`.

**Comment by gallizoltan** [comment]
This happened when I first started `v22.11` yesterday with an up-to-date `plugins` folder.

```
2022-12-03T16:30:31.219Z INFO    lightningd: Updating database from version 199 to 212
2022-12-03T16:30:57.140Z INFO    plugin-backup.py: root        : Comparing backup version 25351135 versus first write version 25351136
2022-12-03T16:30:57.140Z INFO    plugin-backup.py: Comparing backup version 25351135 versus first write version 25351136
2022-12-03T16:30:57.140Z INFO    plugin-backup.py: root        : Versions match up
2022-12-03T16:30:57.140Z INFO    plugin-backup.py: Versions match up
2022-12-03T16:31:59.827Z INFO    plugin-bcli: bitcoin-cli initialized and connected to bitcoind.
2022-12-03T16:32:09.780Z **BROKEN** gossipd: gossip_store broadcastable channel_update 23903718 replaces 23902668!
2022-12-03T16:32:09.780Z **BROKEN** gossipd: gossip_store: Bad channel_update (010241312e07a15d31598098049310a7fd0c8205040dd8cbe124d3bd9d24107f25773ab38d16d986cd39666a8003ac37eaa0b5ec215e956a396f3094c9fbe54f58786fe28c0ab6f1b372c1a6a246ae63f74f931e8365e15a089c68d61900000000000b3c910007640000637925df0101009000000000000000010000000200000002000000001dcd6500). Moving to gossip_store.corrupt and truncating
2022-12-03T16:32:10.030Z INFO    plugin-rebalance.py: Plugin rebalance initialized with 0msat base / 600 ppm fee  cltv_final:18  maxhops:7  msatfactor:1.0  erringnodes:5  getroute:getroute_basic  
2022-12-03T16:32:10.036Z INFO    plugin-feeadjuster.py: Plugin feeadjuster initialized (0 base / 600 ppm) with an imbalance of 45%/55%, update_threshold: 2%, update_threshold_abs: 100000000msat, enough_liquidity: 1500000000msat, deactivate_fuzz: None, forward_event_subscription: False, adjustment_method: get_ratio_hard, fee_strategy: get_fees_global, listchannels_by_dst: True,max_htlc_steps: 0
2022-12-03T16:32:10.048Z INFO    plugin-feeadjuster.py: Excluding the channels with the nodes: []
2022-12-03T16:32:10.048Z INFO    lightningd: --------------------------------------------------
2022-12-03T16:32:10.048Z INFO    lightningd: Server started with public key <xxx>, alias <xxx> (color #000000) and lightningd 22.11
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py: Traceback (most recent call last):
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/lightning/contrib/pyln-client/pyln/client/plugin.py\", line 631, in _dispatch_request
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     result = self._exec_func(method.func, request)
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/lightning/contrib/pyln-client/pyln/client/plugin.py\", line 616, in _exec_func
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     return func(*ba.args, **ba.kwargs)
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/lightning/contrib/pyln-client/pyln/client/plugin.py\", line 957, in _init
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     return self._exec_func(self.child_init, request)
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/lightning/contrib/pyln-client/pyln/client/plugin.py\", line 616, in _exec_func
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     return func(*ba.args, **ba.kwargs)
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/plugins/feeadjuster/feeadjuster.py\", line 347, in init
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     feeadjust(plugin)
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/plugins/feeadjuster/feeadjuster.py\", line 266, in feeadjust
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     channels_adjusted += maybe_adjust_fees(plugin, [_scid])
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:   File \"/home/user/plugins/feeadjuster/feeadjuster.py\", line 162, in maybe_adjust_fees
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py:     if setchannelfee(plugin, scid, base, ppm):
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py: TypeError: setchannelfee() missing 2 required positional arguments: 'min_htlc' and 'max_htlc'
2022-12-03T16:32:10.072Z INFO    plugin-feeadjuster.py: 
```

This very same issue was present at the time of the previous release. I mentioned this back then, hoping it gets fixed with time. (Also, I solved it locally for myself, as it is in this PR.)
https://github.com/lightningd/plugins/pull/368#discussion_r956563933

**Comment by m-schmoock** [comment]
@gallizoltan 
I see, shouldn't we address that by making `min_htlc` and `max_htlc` paramter of `setchannelfee` optional in line `113` like this?:
```
def setchannelfee(plugin: Plugin, scid: str, base: int, ppm: int, min_htlc: int = None, max_htlc: int = None):
```

**Comment by gallizoltan** [comment]
> @gallizoltan I see, shouldn't we address that by making `min_htlc` and `max_htlc` paramter of `setchannelfee` optional in line `113` like this?:
> 
> ```
> def setchannelfee(plugin: Plugin, scid: str, base: int, ppm: int, min_htlc: int = None, max_htlc: int = None):
> ```

That can be a solution too. I don't know which way would be better.

**Comment by m-schmoock** [comment]
> That can be a solution too. I don't know which way would be better.

I think it's better to have these parameters optional, as these parameters are optional also on the underlying RPC method, we should do that for the wrapper as well.

**Comment by gallizoltan** [comment]
@m-schmoock Ok, I've updated the PR.

**Comment by m-schmoock** [comment]
@gallizoltan  I found another one:
```
INFO    plugin-feeadjuster.py: Traceback (most recent call last):
INFO    plugin-feeadjuster.py:   File \"/home/pi/.local/lib/python3.7/site-packages/pyln/client/plugin.py\", line 668, in _dispatch_notification
INFO    plugin-feeadjuster.py:     self._exec_func(func, request)
INFO    plugin-feeadjuster.py:   File \"/home/pi/.local/lib/python3.7/site-packages/pyln/client/plugin.py\", line 619, in _exec_func
INFO    plugin-feeadjuster.py:     ret = func(*ba.args, **ba.kwargs)
INFO    plugin-feeadjuster.py:   File \"/home/pi/btcnode.git/install/lightning.plugins.git/feeadjuster/feeadjuster.py\", line 220, in forward_event
INFO    plugin-feeadjuster.py:     plugin.adj_balances[in_scid][\"our\"] += int(forward_event[\"in_msat\"])
INFO    plugin-feeadjuster.py: ValueError: invalid literal for int() with base 10: '840131605msat'
```

Looks like this can be a problem with `pyln-client` as it should have replaced the `_msat` field string by a `Millisatoshi` value. Do you also see these?

**Comment by gallizoltan** [comment]
@m-schmoock This crash doesn't apply to me, I use the `feeadjuster` differently.
I turned off `forward_event_subscription` and I call `feeadjust` in every 15 minutes from a `cronjob`. 😎

**Comment by m-schmoock** [comment]
Thanks for looking anyway.
Will check this on my own, I thing this one maybe pyln related...

**Comment by m-schmoock** [comment]
@gallizoltan It indeed seems like an pyln-client issue or feature. See https://github.com/ElementsProject/lightning/pull/5798

The reason it does not happen on your machine is, that you very likely have `deprecated-apis` enabled, and then you get a number `12345` in the field instead of a string "12345msat`. In this case the current plugin code can do the math on the integers, but just by chance.

**Pull request merged**
