### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by ProofOfKeags**
This won't actually initialize as is. I believe the change proposed will make a `git submodule update --init` work.

### CODE REVIEW

**Comment by ProofOfKeags** [comment]
@m-schmoock can you take a look at this?

**Comment by m-schmoock** [comment]
@ProofOfKeags 

Hi Keagan,
for me it works without the ".git":

```
$ rm -rf python-teos

$ git submodule update --init
Submodule path 'python-teos': checked out '3dc96f5732107afdb4824ce1fefaa45dfc0bb55d'

$ ls python-teos/
common   CONTRIBUTING.md  docker      LICENSE    requirements-dev.txt  setup.py  test
contrib  DEPENDENCIES.md  INSTALL.md  README.md  requirements.txt      teos      watchtower-plugin

$ git --version
git version 2.35.1
```

What git version do you have and what error does it give on your end?

**Comment by m-schmoock** [comment]
Also the submodules contain other repos without the `.git`:
- https://github.com/darosior/pylightning-qt
- https://github.com/niftynei/sitzprobe

**Comment by ProofOfKeags** [comment]
Error:
```
Cloning into '/tmp/c-lightning-wrapper/plugins/python-teos'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'https://github.com/talaia-labs/python-teos/' into submodule path '/tmp/c-lightning-wrapper/plugins/python-teos' failed
Failed to clone 'python-teos' a second time, aborting
Failed to recurse into submodule path 'plugins'
```

Version: 2.30.2

**Comment by ProofOfKeags** [comment]
Looks like dropping the trailing `/` will also do the trick.

**Review by m-schmoock — DISMISSED** [review]
I think this is related to your machine somehow, but we can align this anyway.
Can you change that to `.git` syntax also for sitzprobe in line 3 then?

Thanks

**Comment by ProofOfKeags** [comment]
It probably is related to my older git version. But yes I can change the rest for consistency. I think it'll be good to be resilient to older git versions on people's machines.

**Comment by m-schmoock** [comment]
thx

**Pull request merged**
