### PR TITLE
drain: fix test and millisatoshi from float

### PR DESCRIPTION
**Pull request by m-schmoock**
There were incompatibilities introduced by main repository changes...

### CODE REVIEW

**Comment by cdecker** [comment]
ACK https://github.com/lightningd/plugins/pull/161/commits/8be469db4932eecbe12741d988f4597ddc1086df

**Comment by m-schmoock** [comment]
I'm lost here. This Travis seems no longer allow the usage of the LightningNode helpers such as `AttributeError: 'LightningNode' object has no attribute 'fundchannel'`

**Comment by m-schmoock** [comment]
@cdecker this is done. Some tests fail for summary, for which I will now update https://github.com/lightningd/plugins/pull/159 to also fix these.

**Comment by m-schmoock** [comment]
Rebased to master just to see if travis is now happy

**Comment by m-schmoock** [comment]
Seems theres another flake...

**Comment by m-schmoock** [comment]
Will fix a remaining flake on `drain/test_drain.py::test_drain_and_refill`

**Comment by m-schmoock** [comment]
@cdecker can we merge? Last remaining testflake `drain/test_drain.py::test_drain_and_refill` has about 1-2% chance, but this one seems very complex. I will fix it but not now ...

**Review by cdecker — APPROVED** [review]

**Pull request merged**
