### PR TITLE
rebalance: handle HTLC timeout

### PR DESCRIPTION
**Pull request by gallizoltan**
In rare cases, HTLCs can be stuck for days. I don't know why it's happening, maybe it would worth investigating the situation.

My `listpeers` look like this:
```
$ lightning-cli listpeers
<...>
               "htlcs": [
                  {
                     "direction": "out",
                     "id": 6317,
                     "msatoshi": 624610838,
                     "amount_msat": "624610838msat",
                     "expiry": 670920,
                     "payment_hash": "fbc58fcada2d3652c4bfb8f7474f0671b45024dec1f0aee2eb813295cd7c2f0c",
                     "state": "SENT_ADD_ACK_REVOCATION"
                  }
               ]
<...>
               "htlcs": [
                  {
                     "direction": "out",
                     "id": 58395,
                     "msatoshi": 121953259,
                     "amount_msat": "121953259msat",
                     "expiry": 669832,
                     "payment_hash": "f19587efc60bae52e87b46ff8fe7eb019ca82f99cc0fbe94bcaa428c759d045d",
                     "state": "SENT_REMOVE_ACK_COMMIT"
                  }
               ]
<...>
```

### CODE REVIEW

**Comment by gallizoltan** [comment]
@m-schmoock what do you think about this? :)

**Comment by m-schmoock** [comment]
ACK adeba7f

**Comment by m-schmoock** [comment]
@gallizoltan thanks. Do you experience the "stuck HTLCs" in tandem with closing channels, or do they resolve just fine after a couple of days?

**Comment by gallizoltan** [comment]
@m-schmoock Thank you for the merge! No closing channels here lately. Only "stuck HTLCs" which resolve in a couple of days.

**Pull request merged**
